### PR TITLE
Add indentation option to CLI

### PR DESCRIPTION
**Pull request by SimonDegraeve**

### CODE REVIEW

**Comment by patrickkettner** [comment]
great idea! there are some issues with the tests, however. Could you look into it?

It may also be worthwhile to do a [check](https://github.com/bcoe/yargs#checkfn) to ensure its a number, and not a string

**Comment by SimonDegraeve** [comment]
I will look at those tests later. Need to catch a flight now.

**Comment by patrickkettner** [comment]
Sounds great – safe travels

**Comment by SimonDegraeve** [comment]
Back on the ground ;-)
I added some tests, it should be ready to be merged.

**Comment by SimonDegraeve** [comment]
PS: Is there a way to test on travis from the local repo before commit? Because the tests have passed on my computer, and turns out they failed in travis...

**Comment by devinivy** [comment]
I'd suggest making sure you have the latest version of `lab`.

**Comment by SimonDegraeve** [comment]
lab 5.14.0 (latest)
node 0.12.7 (latest)

And when running the tests, the package doesn't use a global version of lab anyway it is the one from `package.json`which is the latest...

So I guess there is no magic trick that I am not aware of like `pre-test on remote` before `commit`...

**Comment by SimonDegraeve** [comment]
I mean I know you can use `git hooks` for that, but I am just curious is there is something else I don't know.

**Comment by patrickkettner** [comment]
@SimonDegraeve there is not a way to test on travis, per se. If I had to guess, you were testing on a single version of node and it was failing on the other?

either way - great work!

**Pull request merged**
